################################################################################
# training parameters
################################################################################
train:
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 150
  lr: 0.01              # sgd learning rate
  wup_epochs: 1          # warmup during first XX epochs (can be float)
  momentum: 0.9          # sgd momentum
  lr_decay: 0.99         # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.0001        # weight decay
  batch_size: 4         # batch size
  report_batch: 10        # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  save_summary: False    # Summary of weight histograms for tensorboard
  save_scans: True       # False doesn't save anything, True saves some
    # sample images (one per batch of the last calculated batch)
  # in log folder
  show_scans: False      # show scans during training
  workers: 2            # number of threads to get data

################################################################################
# postproc parameters
################################################################################
post:
  CRF:
    use: False
    train: True
    params: False # this should be a dict when in use
  KNN:
    use: True # This parameter default is false
    params:
      knn: 5
      search: 5
      sigma: 1.0
      cutoff: 1.0

################################################################################
# classification head parameters
################################################################################
# dataset (to find parser)
dataset:
  labels: "carla"
  scans: "carla"
  max_points: 1097152 # max of any scan in dataset
  sensor:
    name: "HDL64"
    type: "spherical" # projective
    fov_up: 15 # 10
    fov_down: -15 # -20
    img_prop:
      width: 2048
      height: 64
    img_means: #range,x,y,z,signal
#      - 0.0
#      - 0.0
#      - 0.0
#      - 0.0
#      - 0.0
      - 35.2812
      - 0.6171
      - 0.3594
      - -0.2803
      - 0.9102
    img_stds: #range,x,y,z,signal
#      - 1.0
#      - 1.0
#      - 1.0
#      - 1.0
#      - 1.0
      - 21.2873
      - 12.8124
      - 11.4528
      - 1.6485
      - 0.2675
